version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6
        auth:
          username: FreakScene999
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: python3.6 test_calculations.py
